export const ErrorCodes = {
  SCHEMA_VALIDATION_FAILED: 'SCHEMA_VALIDATION_FAILED',
  BUSINESS_RULE_VIOLATED: 'BUSINESS_RULE_VIOLATED',
  GRANTED_EVENT_NOT_FOUND: 'GRANTED_EVENT_NOT_FOUND',
  ALREADY_REVOKED: 'ALREADY_REVOKED',
  PURPOSE_DEPRECATED: 'PURPOSE_DEPRECATED',
  SEQUENCE_GAP: 'SEQUENCE_GAP',
  CHAIN_HASH_MISMATCH: 'CHAIN_HASH_MISMATCH',
  INVALID_SUPERSEDES_REFERENCE: 'INVALID_SUPERSEDES_REFERENCE',
  MISSING_SUPERSEDES: 'MISSING_SUPERSEDES',
  DUPLICATE_PURPOSE_IN_POLICY: 'DUPLICATE_PURPOSE_IN_POLICY',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
